# Generated by Django 3.0.8 on 2020-07-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothstylepatterncolourimage',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='clothstylecolourimage',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
